changes in dotfiles

diff --git a/.local/bin/dmenu_calculator b/.local/bin/dmenu_calculator
--- a/.local/bin/dmenu_calculator
+++ b/.local/bin/dmenu_calculator
@@ -1,60 +1,47 @@
 #!/usr/bin/env bash
-# Based on https://github.com/sumnerevans/menu-calc
-# A Dmenu Script for a quick calculator
 
-# Dependencies: xclip, bc
+# https://github.com/onespaceman/menu-calc
+# Calculator for use with rofi/dmenu(2)
+# Copying to the clipboard requires xclip
 
 usage() {
-    echo "$(tput bold)DmenuCalculator$(tput sgr0)"
-    echo "A Simple Calculator for Dmenu"
-    echo
-    echo "$(tput bold)Usage:$(tput sgr0)"
-    echo "    = 4+2"
-    echo "    = (4+2)/(4+3)"
-    echo "    = 4^2"
-    echo "    = sqrt(4)"
-    echo "    = c(2)"
+    echo "    $(tput bold)menu calc$(tput sgr0)
+    A calculator for use with Rofi or dmenu(2)
+    Basic usage:
+    = 4+2
+    = (4+2)/(4+3)
+    = 4^2
+    = sqrt(4)
+    = c(2)
+    The answer can be used for further calculations
+    The expression may need quotation marks if
+    launched outside of Rofi/dmenu"
+    exit
 }
 
-# Process CLI parameters
-for var in "$@"
-do
-    case $var in
-        -h|--help) usage ;;
-        -d=*|--dmenu=*)
-            menu=$(echo $var | cut -d'=' -f 2);
-            ;;
-        --) break ;;
-    esac
-done
-
-# Grab the answer
-answer=$(echo "$1" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
+case $1 in
+    -h|--help) usage ;;
+esac
 
 # Path to menu application
-if [ ! -n "${menu+1}" ]; then
-    if [[ -n $(command -v rofi) ]]; then
-        menu="$(command -v rofi)"
-    elif [[ -n $(command -v dmenu) ]]; then
-        menu=$(command -v dmenu)
-    else
-        >&2 echo "Rofi or dmenu not found"
-        exit
-    fi
+if [[ -n $(command -v rofi) ]]; then
+    menu="$(command -v rofi) -dmenu"
+elif [[ -n $(command -v dmenu) ]]; then
+    menu="$(command -v dmenu)"
+else
+    echo >&2 "Rofi or dmenu not found"
+    exit
 fi
 
-# Determine args to pass to dmenu/rofi
-while [[ $# -gt 0 && $1 != "--" ]]; do
-    shift
-done
-[[ $1 == "--" ]] && shift
+answer=$(echo "$@" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
 
-action=$(echo -e "Copy to clipboard\nClear\nClose" | $menu "$@" -p "= $answer")
+action=$(echo -e "Copy to clipboard\nClear\nClose" |
+$menu -p "= $answer")
 
 case $action in
-    "Clear") $0 "--dmenu=$menu" "--" "$@" ;;
-    "Copy to clipboard") echo -n "$answer" | xclip -selection clipboard ;;
+    "Clear") $0 ;;
+    "Copy to clipboard") echo -n "$answer" | xclip ;;
     "Close") ;;
     "") ;;
-    *) $0 "$answer $action" "--dmenu=$menu" "--" "$@" ;;
+    *) $0 "$answer $action" ;;
 esac
